import type { AIModel, ModelSettingDef } from "../../types/ai.js";
import { mkAspectRatio, mkDurationSelect, mkDurationSlider } from "./_helpers.js";

/** FLUX.2 [dev] generation controls. */
const FLUX_SETTINGS: ModelSettingDef[] = [
  {
    key: "num_inference_steps",
    label: "Шаги генерации",
    description:
      "Количество итераций обработки: больше шагов — детальнее и качественнее, но медленнее.",
    type: "slider",
    min: 1,
    max: 50,
    step: 1,
    default: 28,
  },
  {
    key: "guidance_scale",
    label: "Следование промпту (CFG)",
    description:
      "Насколько строго ИИ следует вашему тексту. Высокие значения — буквально, низкие — с творческой интерпретацией.",
    type: "slider",
    min: 0,
    max: 10,
    step: 0.5,
    default: 2.5,
  },
  {
    key: "acceleration",
    label: "Ускорение",
    description:
      "Скорость генерации: none — максимальное качество, regular — баланс, high — быстро.",
    type: "select",
    options: [
      { value: "none", label: "None" },
      { value: "regular", label: "Regular" },
      { value: "high", label: "High" },
    ],
    default: "regular",
  },
  {
    key: "enable_prompt_expansion",
    label: "Расширение промпта",
    description: "Автоматически дополняет промпт для улучшения результата.",
    type: "toggle",
    default: false,
  },
  {
    key: "enable_safety_checker",
    label: "Фильтр безопасности",
    description: "Фильтрация нежелательного контента.",
    type: "toggle",
    default: true,
  },
  {
    key: "output_format",
    label: "Формат файла",
    description: "Формат результирующего изображения.",
    type: "select",
    options: [
      { value: "png", label: "PNG" },
      { value: "jpeg", label: "JPEG" },
      { value: "webp", label: "WebP" },
    ],
    default: "png",
  },
  {
    key: "seed",
    label: "Seed",
    description: "Фиксированный seed для воспроизводимости результата. Пусто — случайный.",
    type: "number",
    min: 0,
    default: null,
  },
];

/** FLUX.2 [pro] generation controls. */
const FLUX_PRO_SETTINGS: ModelSettingDef[] = [
  {
    key: "safety_tolerance",
    label: "Уровень допустимости",
    description: "Строгость фильтрации контента: 1 — максимальная строгость, 5 — минимальная.",
    type: "select",
    options: [
      { value: "1", label: "1 — Strict" },
      { value: "2", label: "2" },
      { value: "3", label: "3" },
      { value: "4", label: "4" },
      { value: "5", label: "5 — Permissive" },
    ],
    default: "2",
  },
  {
    key: "enable_safety_checker",
    label: "Фильтр безопасности",
    description: "Фильтрация нежелательного контента.",
    type: "toggle",
    default: true,
  },
  {
    key: "output_format",
    label: "Формат файла",
    description: "Формат результирующего изображения.",
    type: "select",
    options: [
      { value: "jpeg", label: "JPEG" },
      { value: "png", label: "PNG" },
    ],
    default: "jpeg",
  },
  {
    key: "seed",
    label: "Seed",
    description: "Фиксированный seed для воспроизводимости результата. Пусто — случайный.",
    type: "number",
    min: 0,
    default: null,
  },
];

/** Ideogram v3 — shared generation controls (quality / balanced / turbo). */
const IDEOGRAM_SETTINGS: ModelSettingDef[] = [
  mkAspectRatio([
    "1:1",
    "4:3",
    "3:4",
    "16:9",
    "9:16",
    "2:3",
    "3:2",
    "4:5",
    "5:4",
    "2:1",
    "1:2",
    "16:10",
    "10:16",
    "3:1",
    "1:3",
  ]),
  {
    key: "resolution",
    label: "Точное разрешение",
    description:
      "Задаёт точный размер в пикселях. Переопределяет aspect ratio. Оставьте None для автоматического выбора.",
    type: "select",
    options: [
      { value: "None", label: "None (авто)" },
      { value: "1024x1024", label: "1024×1024 (1:1)" },
      { value: "1280x768", label: "1280×768 (5:3)" },
      { value: "768x1280", label: "768×1280 (3:5)" },
      { value: "1344x768", label: "1344×768 (16:9)" },
      { value: "768x1344", label: "768×1344 (9:16)" },
      { value: "1216x832", label: "1216×832 (3:2)" },
      { value: "832x1216", label: "832×1216 (2:3)" },
      { value: "1152x896", label: "1152×896 (4:3)" },
      { value: "896x1152", label: "896×1152 (3:4)" },
      { value: "1088x896", label: "1088×896 (5:4)" },
      { value: "896x1088", label: "896×1088 (4:5)" },
      { value: "1536x640", label: "1536×640 (2.4:1)" },
      { value: "640x1536", label: "640×1536 (1:2.4)" },
    ],
    default: "None",
  },
  {
    key: "style_type",
    label: "Стиль",
    description: "Художественное направление изображения.",
    type: "select",
    options: [
      { value: "None", label: "None" },
      { value: "Auto", label: "Auto" },
      { value: "General", label: "General" },
      { value: "Realistic", label: "Realistic" },
      { value: "Design", label: "Design" },
    ],
    default: "None",
  },
  {
    key: "style_preset",
    label: "Художественный пресет",
    description: "Готовый художественный стиль для изображения (только модели V3).",
    type: "select",
    options: [
      { value: "None", label: "None" },
      { value: "80s Illustration", label: "80s Illustration" },
      { value: "90s Nostalgia", label: "90s Nostalgia" },
      { value: "Abstract Organic", label: "Abstract Organic" },
      { value: "Analog Nostalgia", label: "Analog Nostalgia" },
      { value: "Art Brut", label: "Art Brut" },
      { value: "Art Deco", label: "Art Deco" },
      { value: "Art Poster", label: "Art Poster" },
      { value: "Aura", label: "Aura" },
      { value: "Avant Garde", label: "Avant Garde" },
      { value: "Bauhaus", label: "Bauhaus" },
      { value: "Blueprint", label: "Blueprint" },
      { value: "Blurry Motion", label: "Blurry Motion" },
      { value: "Bright Art", label: "Bright Art" },
      { value: "C4D Cartoon", label: "C4D Cartoon" },
      { value: "Children's Book", label: "Children's Book" },
      { value: "Collage", label: "Collage" },
      { value: "Coloring Book I", label: "Coloring Book I" },
      { value: "Coloring Book II", label: "Coloring Book II" },
      { value: "Cubism", label: "Cubism" },
      { value: "Dark Aura", label: "Dark Aura" },
      { value: "Doodle", label: "Doodle" },
      { value: "Double Exposure", label: "Double Exposure" },
      { value: "Dramatic Cinema", label: "Dramatic Cinema" },
      { value: "Editorial", label: "Editorial" },
      { value: "Emotional Minimal", label: "Emotional Minimal" },
      { value: "Ethereal Party", label: "Ethereal Party" },
      { value: "Expired Film", label: "Expired Film" },
      { value: "Flat Art", label: "Flat Art" },
      { value: "Flat Vector", label: "Flat Vector" },
      { value: "Forest Reverie", label: "Forest Reverie" },
      { value: "Geo Minimalist", label: "Geo Minimalist" },
      { value: "Glass Prism", label: "Glass Prism" },
      { value: "Golden Hour", label: "Golden Hour" },
      { value: "Graffiti I", label: "Graffiti I" },
      { value: "Graffiti II", label: "Graffiti II" },
      { value: "Halftone Print", label: "Halftone Print" },
      { value: "High Contrast", label: "High Contrast" },
      { value: "Hippie Era", label: "Hippie Era" },
      { value: "Iconic", label: "Iconic" },
      { value: "Japandi Fusion", label: "Japandi Fusion" },
      { value: "Jazzy", label: "Jazzy" },
      { value: "Long Exposure", label: "Long Exposure" },
      { value: "Magazine Editorial", label: "Magazine Editorial" },
      { value: "Minimal Illustration", label: "Minimal Illustration" },
      { value: "Mixed Media", label: "Mixed Media" },
      { value: "Monochrome", label: "Monochrome" },
      { value: "Nightlife", label: "Nightlife" },
      { value: "Oil Painting", label: "Oil Painting" },
      { value: "Old Cartoons", label: "Old Cartoons" },
      { value: "Paint Gesture", label: "Paint Gesture" },
      { value: "Pop Art", label: "Pop Art" },
      { value: "Retro Etching", label: "Retro Etching" },
      { value: "Riviera Pop", label: "Riviera Pop" },
      { value: "Spotlight 80s", label: "Spotlight 80s" },
      { value: "Stylized Red", label: "Stylized Red" },
      { value: "Surreal Collage", label: "Surreal Collage" },
      { value: "Travel Poster", label: "Travel Poster" },
      { value: "Vintage Geo", label: "Vintage Geo" },
      { value: "Vintage Poster", label: "Vintage Poster" },
      { value: "Watercolor", label: "Watercolor" },
      { value: "Weird", label: "Weird" },
      { value: "Woodblock Print", label: "Woodblock Print" },
    ],
    default: "None",
  },
  {
    key: "magic_prompt_option",
    label: "Magic Prompt",
    description: "Автоматически улучшает ваш запрос для более красивого и детального результата.",
    type: "select",
    options: [
      { value: "Auto", label: "Auto" },
      { value: "On", label: "On" },
      { value: "Off", label: "Off" },
    ],
    default: "Auto",
  },
  {
    key: "negative_prompt",
    label: "Негативный промпт",
    description: "Что НЕ должно быть на картинке: перечислите нежелательные объекты или стили.",
    type: "text",
    default: "",
  },
  {
    key: "seed",
    label: "Seed",
    description: "Зерно генерации. Одинаковый seed при тех же параметрах даёт похожий результат.",
    type: "number",
    min: 0,
    max: 2147483647,
    default: null,
  },
];

/** Seedream guidance + seed. */
const SEEDREAM_SETTINGS: ModelSettingDef[] = [
  {
    key: "guidance_scale",
    label: "Следование промпту (CFG)",
    description:
      "Насколько строго ИИ следует вашему тексту: высокие значения — буквально, низкие — с творческой интерпретацией.",
    type: "slider",
    min: 1,
    max: 10,
    step: 0.5,
    default: 2.5,
  },
  {
    key: "seed",
    label: "Seed",
    description: "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
    type: "number",
    min: 0,
    max: 2147483647,
    default: null,
  },
];

/** Kling / Kling Pro video settings. */

export const DESIGN_MODELS: Record<string, AIModel> = {
  // ── Дизайн ────────────────────────────────────────────────────────────────
  // Media models have no per-token pricing; cost is driven by costUsdPerRequest.
  // Values are mid-range provider prices used as break-even basis.
  "nano-banana-pro": {
    id: "nano-banana-pro",
    name: "🍌 Nano Banana PRO",
    description:
      "Генерирует реалистичные фото и позволяет менять детали прямо словами: «убери фон», «добавь шляпу», «сделай вечер».",
    section: "design",
    provider: "fal",
    familyId: "nano-banana",
    variantLabel: "Pro",
    costVariants: { settingKey: "resolution", map: { "1K": 0.15, "2K": 0.15, "4K": 0.3 } },
    costUsdPerRequest: 0.15,
    costAddons: [{ settingKey: "enable_web_search", map: { true: 0.015 } }],
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    settings: [
      mkAspectRatio(["21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"]),
      {
        key: "safety_tolerance",
        label: "Допустимый контент",
        description: "1 — строгая фильтрация, 6 — минимальная. По умолчанию 4.",
        type: "slider",
        min: 1,
        max: 6,
        step: 1,
        default: 4,
      },
      {
        key: "resolution",
        label: "Разрешение",
        description:
          "Детализация итогового изображения: 1K — стандарт, 4K — максимальные детали. Влияет на цену.",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
      {
        key: "output_format",
        label: "Формат файла",
        description:
          "PNG — без потери качества, JPEG — компактнее, WebP — баланс качества и размера.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
          { value: "webp", label: "WebP" },
        ],
        default: "png",
      },
      {
        key: "enable_web_search",
        label: "Поиск в интернете",
        description:
          "Разрешить модели обращаться к интернету для уточнения деталей промпта. Влияет на цену.",
        type: "toggle",
        default: false,
      },
    ],
  },

  "nano-banana-2": {
    id: "nano-banana-2",
    name: "🍌 Nano Banana 2",
    description:
      "Генерирует реалистичные фото и редактирует их по текстовым командам. Поддерживает поиск в интернете и усиленное мышление для точного следования промпту.",
    section: "design",
    provider: "fal",
    familyId: "nano-banana",
    variantLabel: "Standard",
    // 0.5K = ×0.75, 1K = base $0.08, 2K = ×1.5, 4K = ×2
    costVariants: {
      settingKey: "resolution",
      map: { "0.5K": 0.06, "1K": 0.08, "2K": 0.12, "4K": 0.16 },
    },
    costUsdPerRequest: 0.08,
    costAddons: [
      { settingKey: "enable_web_search", map: { true: 0.015 } },
      { settingKey: "thinking_level", map: { high: 0.002 } },
    ],
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    settings: [
      mkAspectRatio(["21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"]),
      {
        key: "safety_tolerance",
        label: "Допустимый контент",
        description: "1 — строгая фильтрация, 6 — минимальная. По умолчанию 4.",
        type: "slider",
        min: 1,
        max: 6,
        step: 1,
        default: 4,
      },
      {
        key: "resolution",
        label: "Разрешение",
        description:
          "Детализация итогового изображения: 0.5K — быстро, 1K — стандарт, 4K — максимальные детали. Влияет на цену.",
        type: "select",
        options: [
          { value: "0.5K", label: "0.5K" },
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
      {
        key: "output_format",
        label: "Формат файла",
        description:
          "PNG — без потери качества, JPEG — компактнее, WebP — баланс качества и размера.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
          { value: "webp", label: "WebP" },
        ],
        default: "png",
      },
      {
        key: "enable_web_search",
        label: "Поиск в интернете",
        description:
          "Разрешить модели обращаться к интернету для уточнения деталей промпта. Влияет на цену.",
        type: "toggle",
        default: false,
      },
      {
        key: "thinking_level",
        label: "Уровень мышления",
        description:
          "Minimal — лёгкое усиление следования инструкциям, High — глубокий анализ промпта. Отключить — без дополнительного мышления. Влияет на цену.",
        type: "select",
        options: [
          { value: "", label: "Отключено" },
          { value: "minimal", label: "Minimal" },
          { value: "high", label: "High" },
        ],
        default: "",
      },
    ],
  },
  midjourney: {
    id: "midjourney",
    name: "🎨 MidJourney v7",
    description:
      "Создаёт самые красивые и стильные изображения. Лучший выбор для арта, иллюстраций и эффектных визуалов.",
    section: "design",
    provider: "midjourney",
    costUsdPerRequest: 0.089,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "3:2",
      "2:3",
      "4:5",
      "5:4",
      "21:9",
      "9:21",
      "custom",
    ],
    settings: [
      mkAspectRatio([
        "1:1",
        "16:9",
        "9:16",
        "4:3",
        "3:4",
        "3:2",
        "2:3",
        "4:5",
        "5:4",
        "21:9",
        "9:21",
        "custom",
      ]),
      {
        key: "model",
        label: "Модель",
        description: "dev — выше качество (~28 шагов), schnell — быстрая (~4 шага).",
        type: "select",
        options: [
          { value: "dev", label: "Dev" },
          { value: "schnell", label: "Schnell" },
        ],
        default: "dev",
      },
      {
        key: "num_inference_steps",
        label: "Шаги генерации",
        description: "Количество шагов денойзинга. Больше шагов — детальнее, но дольше.",
        type: "slider",
        min: 1,
        max: 50,
        step: 1,
        default: 28,
      },
      {
        key: "guidance_scale",
        label: "Guidance Scale",
        description: "Насколько строго соблюдается промпт. Меньше — реалистичнее (рек. 2–3.5).",
        type: "slider",
        min: 0,
        max: 10,
        step: 0.5,
        default: 3,
      },
      {
        key: "prompt_strength",
        label: "Сила промпта (img2img)",
        description: "Степень изменения при img2img. 1.0 = полная замена, 0 = оригинал.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.8,
      },
      {
        key: "go_fast",
        label: "Быстрый режим",
        description: "fp8-квантизация вместо bf16. Быстрее, чуть ниже качество.",
        type: "toggle",
        default: false,
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "webp", label: "WebP" },
          { value: "jpg", label: "JPG" },
          { value: "png", label: "PNG" },
        ],
        default: "webp",
      },
      {
        key: "output_quality",
        label: "Качество вывода",
        description: "Качество сжатия (0–100). Не влияет на PNG.",
        type: "slider",
        min: 0,
        max: 100,
        step: 1,
        default: 80,
      },
      {
        key: "extra_lora",
        label: "Дополнительная LoRA",
        description: "URL или путь к LoRA-весам (HuggingFace, CivitAI, Replicate, .safetensors).",
        type: "text",
        default: null,
      },
      {
        key: "lora_scale",
        label: "Сила LoRA",
        description: "Интенсивность основной LoRA. Оптимально: 0–1.",
        type: "slider",
        min: -1,
        max: 3,
        step: 0.1,
        default: 1,
      },
      {
        key: "extra_lora_scale",
        label: "Сила доп. LoRA",
        description: "Интенсивность дополнительной LoRA. Оптимально: 0–1.",
        type: "slider",
        min: -1,
        max: 3,
        step: 0.1,
        default: 1,
      },
      {
        key: "seed",
        label: "Seed",
        description: "Фиксированный seed для воспроизводимости результата.",
        type: "number",
        min: 0,
        default: null,
      },
      {
        key: "disable_safety_checker",
        label: "Отключить фильтр",
        description: "Отключить проверку безопасности контента.",
        type: "toggle",
        default: false,
      },
    ],
  },
  "gpt-image-1.5": {
    id: "gpt-image-1.5",
    name: "🖼️ GPT Image 1.5",
    description:
      "Лучше всех понимает сложные текстовые запросы. Точно рисует то, что вы описали, включая текст на картинках.",
    section: "design",
    provider: "openai",
    // Точная цена определяется адаптером на основе quality × size. Базовое значение: medium 1024×1024.
    costUsdPerRequest: 0.034,
    costVariants: {
      settingKey: "quality",
      map: { low: 0.009, medium: 0.034, high: 0.133 },
    },
    costMatrix: {
      dims: ["quality", "size"],
      table: {
        low__1024x1024: 0.009,
        low__1536x1024: 0.013,
        low__1024x1536: 0.013,
        medium__1024x1024: 0.034,
        medium__1536x1024: 0.05,
        medium__1024x1536: 0.05,
        high__1024x1024: 0.133,
        high__1536x1024: 0.2,
        high__1024x1536: 0.2,
        auto__1024x1024: 0.034,
        auto__1536x1024: 0.05,
        auto__1024x1536: 0.05,
      },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: null,
    settings: [
      {
        key: "size",
        label: "Размер",
        description:
          "1024×1024 — квадрат, 1536×1024 — горизонталь, 1024×1536 — вертикаль. Влияет на цену.",
        type: "select",
        options: [
          { value: "1024x1024", label: "1024 × 1024" },
          { value: "1536x1024", label: "1536 × 1024 (16:9)" },
          { value: "1024x1536", label: "1024 × 1536 (9:16)" },
        ],
        default: "1024x1024",
      },
      {
        key: "quality",
        label: "Качество",
        description:
          "low ($0.009–$0.013) — быстро, medium ($0.034–$0.05) — баланс, high ($0.133–$0.20) — максимум.",
        type: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "medium", label: "Medium" },
          { value: "high", label: "High" },
          { value: "auto", label: "Auto" },
        ],
        default: "medium",
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат сохраняемого изображения. PNG поддерживает прозрачность.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
          { value: "webp", label: "WebP" },
        ],
        default: "png",
      },
      {
        key: "output_compression",
        label: "Сжатие",
        description:
          "Степень сжатия для JPEG и WebP (0 — без потерь, 100 — максимальное сжатие). Не влияет на PNG.",
        type: "slider",
        min: 0,
        max: 100,
        step: 1,
        default: 100,
      },
      {
        key: "background",
        label: "Фон",
        description: "transparent — прозрачный фон (только PNG/WebP), opaque — непрозрачный.",
        type: "select",
        options: [
          { value: "auto", label: "Auto" },
          { value: "opaque", label: "Opaque" },
          { value: "transparent", label: "Transparent" },
        ],
        default: "auto",
      },
      {
        key: "moderation",
        label: "Модерация",
        description: "low — ослабленная фильтрация контента, auto — стандартная.",
        type: "select",
        options: [
          { value: "auto", label: "Auto" },
          { value: "low", label: "Low" },
        ],
        default: "auto",
      },
    ],
  },
  "stable-diffusion": {
    id: "stable-diffusion",
    name: "🌊 Stable Diffusion 3.5",
    description:
      "Генерирует детальные изображения в любом стиле: от фотореализма до аниме и фэнтези. Отличается гибкостью.",
    section: "design",
    provider: "replicate",
    costUsdPerRequest: 0.065,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // Replicate/SDXL accepts arbitrary dimensions — offer extended set
    supportedAspectRatios: ["1:1", "16:9", "21:9", "2:3", "3:2", "4:5", "5:4", "9:16", "9:21"],
    settings: [
      mkAspectRatio(["1:1", "16:9", "21:9", "2:3", "3:2", "4:5", "5:4", "9:16", "9:21"]),
      {
        key: "negative_prompt",
        label: "Негативный промпт",
        description:
          "Что НЕ должно быть на картинке: перечислите нежелательные объекты, стили или черты.",
        type: "text",
        default: "",
      },
      {
        key: "cfg",
        label: "Следование промпту (CFG)",
        description:
          "Насколько строго ИИ следует тексту. Высокие значения — буквально, низкие — с творческой интерпретацией.",
        type: "slider",
        min: 1,
        max: 10,
        step: 0.5,
        default: 5,
      },
      {
        key: "prompt_strength",
        label: "Сила промпта (img2img)",
        description:
          "Степень изменения при img2img. 1.0 = полное изменение оригинала, 0 = без изменений.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.85,
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "webp", label: "WebP" },
          { value: "jpg", label: "JPG" },
          { value: "png", label: "PNG" },
        ],
        default: "webp",
      },
      {
        key: "seed",
        label: "Seed",
        description: "Фиксированный seed для воспроизводимости результата.",
        type: "number",
        min: 0,
        default: null,
      },
    ],
  },
  "dall-e-3": {
    id: "dall-e-3",
    name: "🎯 DALL-E 3 Turbo",
    description:
      "Простой и понятный генератор от OpenAI. Хорошо понимает запросы на любом языке, отлично для быстрых идей.",
    section: "design",
    provider: "openai",
    // Base: standard 1024×1024. Exact cost = quality × size (see costMatrix).
    costUsdPerRequest: 0.04,
    costVariants: { settingKey: "quality", map: { standard: 0.04, hd: 0.08 } },
    costMatrix: {
      dims: ["quality", "aspect_ratio"],
      table: {
        "standard__1:1": 0.04,
        "standard__16:9": 0.08,
        "standard__9:16": 0.08,
        "hd__1:1": 0.08,
        "hd__16:9": 0.12,
        "hd__9:16": 0.12,
      },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // DALL-E 3 only supports exactly 3 sizes
    supportedAspectRatios: ["1:1", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "16:9", "9:16"]),
      {
        key: "quality",
        label: "Качество",
        description: "Standard — быстрее и дешевле, HD — более детальная и сложная картинка.",
        type: "select",
        options: [
          { value: "standard", label: "Standard" },
          { value: "hd", label: "HD" },
        ],
        default: "standard",
      },
      {
        key: "style",
        label: "Стиль",
        description:
          "Vivid — насыщенные цвета, яркий и выразительный результат. Natural — более спокойный и реалистичный.",
        type: "select",
        options: [
          { value: "vivid", label: "Vivid" },
          { value: "natural", label: "Natural" },
        ],
        default: "vivid",
      },
    ],
  },
  ideogram: {
    id: "ideogram",
    name: "✍️ Ideogram v3.0",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров, обложек и рекламы. Максимальное качество.",
    section: "design",
    provider: "ideogram",
    familyId: "ideogram",
    variantLabel: "Quality",
    costUsdPerRequest: 0.09,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "2:1",
      "1:2",
      "16:10",
      "10:16",
      "3:1",
      "1:3",
    ],
    settings: IDEOGRAM_SETTINGS,
  },
  "ideogram-balanced": {
    id: "ideogram-balanced",
    name: "✍️ Ideogram v3.0",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров, обложек и рекламы. Баланс качества и скорости.",
    section: "design",
    provider: "ideogram",
    familyId: "ideogram",
    variantLabel: "Balanced",
    costUsdPerRequest: 0.06,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "2:1",
      "1:2",
      "16:10",
      "10:16",
      "3:1",
      "1:3",
    ],
    settings: IDEOGRAM_SETTINGS,
  },
  "ideogram-turbo": {
    id: "ideogram-turbo",
    name: "✍️ Ideogram v3.0",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров, обложек и рекламы. Быстрая и бюджетная версия.",
    section: "design",
    provider: "ideogram",
    familyId: "ideogram",
    variantLabel: "Turbo",
    costUsdPerRequest: 0.03,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "2:1",
      "1:2",
      "16:10",
      "10:16",
      "3:1",
      "1:3",
    ],
    settings: IDEOGRAM_SETTINGS,
  },
  "imagen-4": {
    id: "imagen-4",
    name: "🔮 Imagen 4",
    description:
      "Новая модель генерации изображений от Google. Высокая фотореалистичность и точное следование текстовым описаниям.",
    section: "design",
    provider: "google",
    costUsdPerRequest: 0.04, // default: standard tier; fast=$0.02, ultra=$0.06
    costVariants: { settingKey: "mode", map: { fast: 0.02, standard: 0.04, ultra: 0.06 } },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "mode",
        label: "Качество / скорость",
        description:
          "fast — быстро и дёшево, standard — стандарт, ultra — максимальное разрешение до 2.8K. Влияет на цену.",
        type: "select",
        options: [
          { value: "fast", label: "Fast" },
          { value: "standard", label: "Standard" },
          { value: "ultra", label: "Ultra" },
        ],
        default: "standard",
      },
    ],
  },
  flux: {
    id: "flux",
    name: "⚡ FLUX.2",
    description:
      "Максимально реалистичные фото за секунды. Лучший выбор, когда нужно быстро и неотличимо от настоящего снимка.",
    section: "design",
    provider: "fal",
    familyId: "flux",
    versionLabel: "2",
    variantLabel: "Standard",
    costUsdPerRequest: 0,
    costUsdPerMPixel: 0.012, // $0.012/MP, billed as ceil(px/1_000_000)
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // FAL image_size categories: square_hd, landscape_4_3, portrait_4_3, landscape_16_9, portrait_16_9
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]), ...FLUX_SETTINGS],
  },
  "flux-pro": {
    id: "flux-pro",
    name: "⚡ FLUX.2 Pro",
    description:
      "Профессиональная версия FLUX.2 — максимальное качество, точнее следует промпту, поддерживает редактирование загруженных изображений.",
    section: "design",
    provider: "fal",
    familyId: "flux",
    versionLabel: "2",
    variantLabel: "Pro",
    costUsdPerRequest: 0,
    // $0.03 for first MP + $0.015 per extra MP: base=$0.015, perMP=$0.015 → ceil formula
    costUsdPerMPixelBase: 0.015,
    costUsdPerMPixel: 0.015,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]), ...FLUX_PRO_SETTINGS],
  },
  "recraft-v3": {
    id: "recraft-v3",
    name: "🖌️ Recraft v3",
    description:
      "Быстро создаёт иллюстрации, иконки и графику в едином стиле. Отлично подходит для дизайна и презентаций.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v3",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "style",
        label: "Стиль",
        description:
          "Художественное направление: реалистичные фото, цифровые иллюстрации или векторная графика.",
        type: "select",
        options: [
          { value: "realistic_image", label: "Реализм" },
          { value: "digital_illustration", label: "Иллюстрация" },
          { value: "vector_illustration", label: "Вектор" },
        ],
        default: "realistic_image",
      },
      {
        key: "substyle",
        label: "Под-стиль",
        description:
          "Уточняет художественный стиль: b_and_w, hard_flash, pixel_art, grain и другие. Зависит от выбранного стиля.",
        type: "text",
        default: "",
      },
      {
        key: "no_text",
        label: "Без текста",
        description: "Запретить модели добавлять текст, надписи и леттеринг в изображение.",
        type: "toggle",
        default: false,
      },
      {
        key: "artistic_level",
        label: "Художественность",
        description: "0 — близко к реальности, 5 — максимально стилизованно и художественно.",
        type: "slider",
        min: 0,
        max: 5,
        step: 1,
        default: 2,
      },
    ],
  },
  "recraft-v4": {
    id: "recraft-v4",
    name: "🖌️ Recraft V4",
    description:
      "Recraft V4 создан специально для дизайна и маркетинга: чистая композиция, точный рендеринг текста и профессиональная полировка. Результат готов для кампании, презентации или страницы продукта без пост-обработки.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "no_text",
        label: "Без текста",
        description: "Запретить модели добавлять текст, надписи и леттеринг в изображение.",
        type: "toggle",
        default: false,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
      },
    ],
  },
  "recraft-v4-pro": {
    id: "recraft-v4-pro",
    name: "💠 Recraft V4 Pro",
    description:
      "Расширенная версия Recraft V4 с повышенным разрешением и детализацией. Идеальна для ответственных дизайн-проектов, где требуется максимальная визуальная точность — без правок, прямо в производство.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Pro",
    costUsdPerRequest: 0.25,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "no_text",
        label: "Без текста",
        description: "Запретить модели добавлять текст, надписи и леттеринг в изображение.",
        type: "toggle",
        default: false,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
      },
    ],
  },
  "recraft-v4-vector": {
    id: "recraft-v4-vector",
    name: "📐 Recraft V4 Vector (SVG)",
    description:
      "Генерирует масштабируемые SVG-векторы — идеально для логотипов, иллюстраций и иконок. Результат масштабируется без потери качества до любого размера и готов к прямому использованию в вёрстке и полиграфии.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Vector",
    costUsdPerRequest: 0.08,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
      },
    ],
  },
  "recraft-v4-pro-vector": {
    id: "recraft-v4-pro-vector",
    name: "📐 Recraft V4 Pro Vector (SVG)",
    description:
      "Профессиональная векторная генерация с максимальным качеством SVG. Подходит для сложных иллюстраций, брендинга и любого дизайна, требующего безупречной масштабируемости и детализации.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Pro Vector",
    costUsdPerRequest: 0.3,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
      },
    ],
  },
  "seedream-5": {
    id: "seedream-5",
    name: "🛍️ Seedream 5.0 (ByteDance)",
    description:
      "Идеально для товарных фото, одежды и каталогов. Создаёт чистые, профессиональные изображения для продаж.",
    section: "design",
    provider: "fal",
    familyId: "seedream",
    versionLabel: "5.0",
    variantLabel: "Standard",
    costUsdPerRequest: 0.035,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]), ...SEEDREAM_SETTINGS],
  },
  "seedream-4.5": {
    id: "seedream-4.5",
    name: "🛍️ Seedream 4.5",
    description:
      "Предыдущая версия Seedream — чуть проще, но быстрее и дешевле. Подойдёт для массовой генерации товарных фото.",
    section: "design",
    provider: "fal",
    familyId: "seedream",
    versionLabel: "4.5",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]), ...SEEDREAM_SETTINGS],
  },
};
