import type { AIModel } from "../types/ai.js";

export const AI_MODELS: Record<string, AIModel> = {
  // ── GPT / LLM ─────────────────────────────────────────────────────────────
  // LLM models have costUsdPerRequest = 0; cost is entirely token-driven.
  // Per-token prices sourced from provider pricing pages (2026-03-17).
  "gpt-4o": {
    id: "gpt-4o",
    name: "GPT-4o",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.5,
    outputCostUsdPerMToken: 10.0,
    supportsImages: true,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain", // OpenAI Responses API
    contextMaxMessages: 0, // не используется при provider_chain
  },
  "gpt-4o-mini": {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.15,
    outputCostUsdPerMToken: 0.6,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-4o-assistants": {
    id: "gpt-4o-assistants",
    name: "GPT-4o (Assistants)",
    section: "gpt",
    provider: "openai-assistants",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.5,
    outputCostUsdPerMToken: 10.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true, // через Assistant tools
    isAsync: false,
    contextStrategy: "provider_thread", // OpenAI Assistants API
    contextMaxMessages: 0,
  },
  "claude-sonnet": {
    id: "claude-sonnet",
    name: "Claude Sonnet 4.5",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history", // нет серверного контекста
    contextMaxMessages: 50,
  },
  "claude-haiku": {
    id: "claude-haiku",
    name: "Claude Haiku 4.5",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.0,
    outputCostUsdPerMToken: 5.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "gemini-2-flash": {
    id: "gemini-2-flash",
    name: "Gemini 2.0 Flash",
    section: "gpt",
    provider: "google",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.1,
    outputCostUsdPerMToken: 0.4,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  // Note: gemini-2.0-pro was removed by Google; this maps to Gemini 2.5 Pro pricing.
  "gemini-2-pro": {
    id: "gemini-2-pro",
    name: "Gemini 2.5 Pro",
    section: "gpt",
    provider: "google",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.25,
    outputCostUsdPerMToken: 10.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "qwen-max": {
    id: "qwen-max",
    name: "Qwen Max",
    section: "gpt",
    provider: "alibaba",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.2,
    outputCostUsdPerMToken: 6.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },

  // ── Дизайн ────────────────────────────────────────────────────────────────
  // Media models have no per-token pricing; cost is driven by costUsdPerRequest.
  // Values are mid-range provider prices used as break-even basis.
  "dall-e-3": {
    id: "dall-e-3",
    name: "DALL-E 3",
    section: "design",
    provider: "openai",
    costUsdPerRequest: 0.04, // $0.040 standard 1024×1024
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  midjourney: {
    id: "midjourney",
    name: "MidJourney",
    section: "design",
    provider: "midjourney",
    costUsdPerRequest: 0.03, // ~$0.01–$0.05 via 3rd-party API
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  flux: {
    id: "flux",
    name: "Flux",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.01, // fal.ai ~$0.003–$0.030
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  ideogram: {
    id: "ideogram",
    name: "IdeoGram",
    section: "design",
    provider: "ideogram",
    costUsdPerRequest: 0.04, // ~$0.020–$0.060
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "imagen-4": {
    id: "imagen-4",
    name: "Imagen 4",
    section: "design",
    provider: "google",
    costUsdPerRequest: 0.03, // Vertex AI ~$0.020–$0.040
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "stable-diffusion": {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    section: "design",
    provider: "replicate",
    costUsdPerRequest: 0.003, // Replicate ~$0.002–$0.005
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },

  // ── Видео ─────────────────────────────────────────────────────────────────
  kling: {
    id: "kling",
    name: "Kling",
    section: "video",
    provider: "kling",
    costUsdPerRequest: 0.525, // 5s clip ~$0.35–$0.70
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  sora: {
    id: "sora",
    name: "SORA",
    section: "video",
    provider: "openai",
    costUsdPerRequest: 0.5, // 5s @ $0.10/s
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  runway: {
    id: "runway",
    name: "RunWay",
    section: "video",
    provider: "runway",
    costUsdPerRequest: 0.75, // 5s clip ~$0.50–$1.00
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  veo: {
    id: "veo",
    name: "Veo",
    section: "video",
    provider: "google",
    costUsdPerRequest: 0.75, // 5s @ $0.15/s
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  luma: {
    id: "luma",
    name: "Luma: DM",
    section: "video",
    provider: "luma",
    costUsdPerRequest: 0.079, // ~$0.033–$0.125/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  minimax: {
    id: "minimax",
    name: "MiniMax",
    section: "video",
    provider: "minimax",
    costUsdPerRequest: 0.25, // ~$0.10–$0.40/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  pika: {
    id: "pika",
    name: "Pika",
    section: "video",
    provider: "pika",
    costUsdPerRequest: 0.25, // ~$0.10–$0.40/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  hailuo: {
    id: "hailuo",
    name: "Hailuo",
    section: "video",
    provider: "hailuo",
    costUsdPerRequest: 0.25, // ~$0.10–$0.40/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  heygen: {
    id: "heygen",
    name: "HeyGen",
    section: "video",
    provider: "heygen",
    costUsdPerRequest: 1.5, // ~$1–$2/min video
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "d-id": {
    id: "d-id",
    name: "D-ID",
    section: "video",
    provider: "d-id",
    costUsdPerRequest: 0.3, // ~$0.10–$0.50/clip
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },

  // ── Аудио ─────────────────────────────────────────────────────────────────
  "tts-openai": {
    id: "tts-openai",
    name: "Синтез речи (OpenAI)",
    section: "audio",
    provider: "openai",
    costUsdPerRequest: 0.0045, // $0.015/1K chars, ~300 chars typical
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "voice-clone": {
    id: "voice-clone",
    name: "Клонирование голоса",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0.072, // ElevenLabs ~$0.054–$0.090 per ~300 chars
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  suno: {
    id: "suno",
    name: "Генерация музыки (Suno)",
    section: "audio",
    provider: "suno",
    costUsdPerRequest: 0.035, // ~$0.030–$0.040/track
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "sounds-el": {
    id: "sounds-el",
    name: "Звуковые эффекты (ElevenLabs)",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0.048, // ElevenLabs ~$0.036–$0.060 per ~200 chars
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
};

// Модели по секции
export const MODELS_BY_SECTION = Object.values(AI_MODELS).reduce(
  (acc, model) => {
    if (!acc[model.section]) acc[model.section] = [];
    acc[model.section].push(model);
    return acc;
  },
  {} as Record<string, AIModel[]>,
);
