import type { AIModel } from "../types/ai.js";

export const AI_MODELS: Record<string, AIModel> = {
  // ── GPT / LLM ─────────────────────────────────────────────────────────────
  // LLM models have costUsdPerRequest = 0; cost is entirely token-driven.
  // Per-token prices sourced from provider pricing pages (2026-03-17).
  // Order matches the mini-app display order.

  // ── GPT 5 ─────────────────────────────────────────────────────────────────
  "gpt-5.4-pro": {
    id: "gpt-5.4-pro",
    name: "GPT 5.4 Pro",
    description: "Самая мощная модель OpenAI, максимальная точность и глубина рассуждений.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 30.0,
    outputCostUsdPerMToken: 120.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-5.4": {
    id: "gpt-5.4",
    name: "GPT 5.4",
    description: "Флагман OpenAI, отличный баланс интеллекта и скорости.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 10.0,
    outputCostUsdPerMToken: 40.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-5.3": {
    id: "gpt-5.3",
    name: "GPT 5.3",
    description: "Предыдущий флагман OpenAI, всё ещё очень сильная модель.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 7.5,
    outputCostUsdPerMToken: 30.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-5-mini": {
    id: "gpt-5-mini",
    name: "GPT 5 Mini",
    description: "Компактная и быстрая, хороша для повседневных задач.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.5,
    outputCostUsdPerMToken: 6.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-5-nano": {
    id: "gpt-5-nano",
    name: "GPT 5 Nano",
    description: "Самая лёгкая и дешёвая в линейке GPT 5, мгновенные ответы.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.15,
    outputCostUsdPerMToken: 0.6,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "o4-mini": {
    id: "o4-mini",
    name: "GPT-o4 Mini",
    description: "Reasoning-модель OpenAI, цепочка рассуждений для сложных задач за низкую цену.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.1,
    outputCostUsdPerMToken: 4.4,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-4o-assistants": {
    id: "gpt-4o-assistants",
    name: "GPT-4o +Internet +File",
    description:
      "Мультимодальная GPT-4o с поиском в интернете и анализом файлов через OpenAI Assistants.",
    section: "gpt",
    provider: "openai-assistants",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.5,
    outputCostUsdPerMToken: 10.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true, // через Assistant tools
    isAsync: false,
    contextStrategy: "provider_thread", // OpenAI Assistants API
    contextMaxMessages: 0,
  },

  // ── Anthropic ─────────────────────────────────────────────────────────────
  "claude-opus": {
    id: "claude-opus",
    name: "Claude 4.6 Opus",
    description:
      "Самая умная модель Anthropic, лучшая для сложных аналитических и творческих задач. Понимает изображения.",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 15.0,
    outputCostUsdPerMToken: 75.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "claude-opus-4-5": {
    id: "claude-opus-4-5",
    name: "Claude 4.5 Opus",
    description:
      "Предыдущий флагман Anthropic, глубокий анализ и длинные тексты. Понимает изображения.",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 15.0,
    outputCostUsdPerMToken: 75.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "claude-sonnet": {
    id: "claude-sonnet",
    name: "Claude 4.6 Sonnet",
    description:
      "Быстрая и умная, лучший баланс цена/качество у Anthropic. Отлично справляется с кодом, текстами и анализом.",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history", // нет серверного контекста
    contextMaxMessages: 50,
  },
  "claude-sonnet-4-5": {
    id: "claude-sonnet-4-5",
    name: "Claude 4.5 Sonnet",
    description: "Надёжная рабочая лошадка Anthropic, отлично для кода и текстов.",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "claude-haiku": {
    id: "claude-haiku",
    name: "Claude 4.5 Haiku",
    description: "Самая быстрая и дешёвая модель Anthropic, мгновенные ответы для простых задач.",
    section: "gpt",
    provider: "anthropic",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.0,
    outputCostUsdPerMToken: 5.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },

  // ── Google Gemini ──────────────────────────────────────────────────────────
  "gemini-3-pro": {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    description:
      "Флагман Google, огромный контекст и мультимодальность. Поддерживает поиск в интернете.",
    section: "gpt",
    provider: "google",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.5,
    outputCostUsdPerMToken: 15.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "gemini-3.1-pro": {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    description:
      "Обновлённый Gemini 3 Pro с улучшенным следованием инструкциям. Поиск в интернете.",
    section: "gpt",
    provider: "google",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 18.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "gemini-2-flash": {
    id: "gemini-2-flash",
    name: "Gemini 2.5 Flash",
    description:
      "Быстрая и дешёвая модель Google с reasoning, отличное соотношение цена/качество. Поддерживает поиск в интернете.",
    section: "gpt",
    provider: "google",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.15,
    outputCostUsdPerMToken: 0.6,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },

  // ── DeepSeek ──────────────────────────────────────────────────────────────
  "deepseek-r1": {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    description:
      "Reasoning-модель из Китая, конкурент o1, сильна в математике и коде. Открытые веса.",
    section: "gpt",
    provider: "deepseek",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.55,
    outputCostUsdPerMToken: 2.19,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "deepseek-v3": {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    description:
      "Быстрая модель, отличная для общих задач и генерации текста при очень низкой стоимости.",
    section: "gpt",
    provider: "deepseek",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.27,
    outputCostUsdPerMToken: 1.1,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },

  // ── xAI Grok ──────────────────────────────────────────────────────────────
  "grok-4": {
    id: "grok-4",
    name: "Grok 4",
    description: "Флагман xAI (Илон Маск), мощные рассуждения с доступом к данным X.",
    section: "gpt",
    provider: "xai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 5.0,
    outputCostUsdPerMToken: 25.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "grok-3": {
    id: "grok-3",
    name: "Grok 3",
    description: "Предыдущий флагман xAI, сильный в анализе и генерации с минимальной цензурой.",
    section: "gpt",
    provider: "xai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "grok-3-deep-search": {
    id: "grok-3-deep-search",
    name: "Grok 3 Deep Search",
    description: "Grok 3 с глубоким поиском по интернету и X в реальном времени.",
    section: "gpt",
    provider: "xai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "grok-3-reasoner": {
    id: "grok-3-reasoner",
    name: "Grok 3 Reasoner",
    description: "Grok 3 с цепочкой рассуждений для сложных логических и математических задач.",
    section: "gpt",
    provider: "xai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "grok-3-image": {
    id: "grok-3-image",
    name: "Grok 3 Images Generation",
    description: "Генерация изображений от xAI, минимальные ограничения на контент.",
    section: "gpt",
    provider: "xai",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },

  // ── Perplexity ────────────────────────────────────────────────────────────
  "perplexity-sonar-pro": {
    id: "perplexity-sonar-pro",
    name: "Perplexity Sonar Pro + Internet",
    description: "Мощный AI-поиск с глубокими ответами. Актуальные данные из интернета.",
    section: "gpt",
    provider: "perplexity",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 3.0,
    outputCostUsdPerMToken: 15.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 20,
  },
  "perplexity-sonar-research": {
    id: "perplexity-sonar-research",
    name: "Perplexity Sonar Deep Research",
    description: "Автономный исследователь, анализирует десятки источников за один запрос.",
    section: "gpt",
    provider: "perplexity",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.0,
    outputCostUsdPerMToken: 8.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 20,
  },
  "perplexity-sonar": {
    id: "perplexity-sonar",
    name: "Perplexity Sonar + Internet",
    description: "Быстрый AI-поиск с актуальными данными из интернета.",
    section: "gpt",
    provider: "perplexity",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.0,
    outputCostUsdPerMToken: 1.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 20,
  },

  // ── Qwen 3 ───────────────────────────────────────────────────────────────
  "qwen-3-max-thinking": {
    id: "qwen-3-max-thinking",
    name: "Qwen 3 Max Thinking",
    description: "Крупнейшая reasoning-модель Alibaba, конкурент GPT и Claude.",
    section: "gpt",
    provider: "alibaba",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 4.0,
    outputCostUsdPerMToken: 16.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "qwen-3-thinking": {
    id: "qwen-3-thinking",
    name: "Qwen 3 Thinking",
    description: "Reasoning-модель Alibaba среднего размера, сильна в коде и математике.",
    section: "gpt",
    provider: "alibaba",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.0,
    outputCostUsdPerMToken: 4.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  "qwen-3": {
    id: "qwen-3",
    name: "Qwen 3",
    description: "Быстрая модель Alibaba, отличная для мультиязычных задач.",
    section: "gpt",
    provider: "alibaba",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.5,
    outputCostUsdPerMToken: 2.0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },

  // ── Legacy / older models (not shown prominently in UI) ───────────────────
  "gpt-4o": {
    id: "gpt-4o",
    name: "GPT-4o",
    description:
      "Флагман OpenAI. Понимает изображения и голос, отлично справляется с анализом, кодом и сложными задачами.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.5,
    outputCostUsdPerMToken: 10.0,
    supportsImages: true,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain", // OpenAI Responses API
    contextMaxMessages: 0, // не используется при provider_chain
  },
  "gpt-4o-mini": {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    description:
      "Лёгкая и быстрая версия GPT-4o. Отлично подходит для простых диалогов и повседневных задач при минимальных затратах.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.15,
    outputCostUsdPerMToken: 0.6,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-4.1": {
    id: "gpt-4.1",
    name: "GPT-4.1",
    description:
      "Обновлённый GPT-4 с улучшенным следованием инструкциям и работой с длинными контекстами. Понимает изображения.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 2.0,
    outputCostUsdPerMToken: 8.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "gpt-4.1-mini": {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    description:
      "Компактная версия GPT-4.1 — отличный баланс качества и цены для повседневных задач. Понимает изображения.",
    section: "gpt",
    provider: "openai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.4,
    outputCostUsdPerMToken: 1.6,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "provider_chain",
    contextMaxMessages: 0,
  },
  "grok-3-mini": {
    id: "grok-3-mini",
    name: "Grok 3 Mini",
    description:
      "Лёгкая версия Grok 3 — быстрая, доступная и хорошо справляется с логическими задачами и программированием.",
    section: "gpt",
    provider: "xai",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0.3,
    outputCostUsdPerMToken: 0.5,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },
  // Note: gemini-2.0-pro was removed by Google; this maps to Gemini 2.5 Pro pricing.
  "gemini-2-pro": {
    id: "gemini-2-pro",
    name: "Gemini 2.5 Pro",
    description:
      "Самая мощная модель Google. Превосходит аналоги в сложных рассуждениях, математике и длинных контекстах. Поддерживает поиск в интернете.",
    section: "gpt",
    provider: "google",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.25,
    outputCostUsdPerMToken: 10.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: true,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 50,
  },
  "qwen-max": {
    id: "qwen-max",
    name: "Qwen Max",
    description:
      "Флагманская модель Alibaba. Сильна в работе с азиатскими языками, кодом, деловыми задачами и длинными документами.",
    section: "gpt",
    provider: "alibaba",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 1.2,
    outputCostUsdPerMToken: 6.0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 40,
  },

  // ── Дизайн ────────────────────────────────────────────────────────────────
  // Media models have no per-token pricing; cost is driven by costUsdPerRequest.
  // Values are mid-range provider prices used as break-even basis.
  "nano-banana-pro": {
    id: "nano-banana-pro",
    name: "🍌 Nano Banana PRO",
    description:
      "Генерирует реалистичные фото и позволяет менять детали прямо словами: «убери фон», «добавь шляпу», «сделай вечер».",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.15,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  midjourney: {
    id: "midjourney",
    name: "🎨 MidJourney v7",
    description:
      "Создаёт самые красивые и стильные изображения. Лучший выбор для арта, иллюстраций и эффектных визуалов.",
    section: "design",
    provider: "midjourney",
    costUsdPerRequest: 0.03,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "gpt-image-1.5": {
    id: "gpt-image-1.5",
    name: "🖼️ GPT Image 1.5",
    description:
      "Лучше всех понимает сложные текстовые запросы. Точно рисует то, что вы описали, включая текст на картинках.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "16:9", "9:16"],
  },
  "stable-diffusion": {
    id: "stable-diffusion",
    name: "🌊 Stable Diffusion 3.5",
    description:
      "Генерирует детальные изображения в любом стиле: от фотореализма до аниме и фэнтези. Отличается гибкостью.",
    section: "design",
    provider: "replicate",
    costUsdPerRequest: 0.003,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // Replicate/SDXL accepts arbitrary dimensions — offer extended set
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3"],
  },
  "dall-e-3": {
    id: "dall-e-3",
    name: "🎯 DALL-E 3 Turbo",
    description:
      "Простой и понятный генератор от OpenAI. Хорошо понимает запросы на любом языке, отлично для быстрых идей.",
    section: "design",
    provider: "openai",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // DALL-E 3 only supports exactly 3 sizes
    supportedAspectRatios: ["1:1", "16:9", "9:16"],
  },
  flux: {
    id: "flux",
    name: "⚡ FLUX.2",
    description:
      "Максимально реалистичные фото за секунды. Лучший выбор, когда нужно быстро и неотличимо от настоящего снимка.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0,
    costUsdPerMPixel: 0.025, // $0.025/MP, billed as ceil(px/1_000_000)
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // FAL image_size categories: square_hd, landscape_4_3, portrait_4_3, landscape_16_9, portrait_16_9
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  ideogram: {
    id: "ideogram",
    name: "✍️ Ideogram v3.0",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров, обложек и рекламы.",
    section: "design",
    provider: "ideogram",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "imagen-4": {
    id: "imagen-4",
    name: "🔮 Imagen 4",
    description:
      "Новая модель генерации изображений от Google. Высокая фотореалистичность и точное следование текстовым описаниям.",
    section: "design",
    provider: "google",
    costUsdPerRequest: 0.03,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "flux-pro": {
    id: "flux-pro",
    name: "⚡ FLUX.1.1 Pro",
    description:
      "Предыдущая версия FLUX — такой же фотореализм, чуть медленнее, но проверенная и стабильная.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0,
    costUsdPerMPixel: 0.04, // $0.04/MP, billed as ceil(px/1_000_000)
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "recraft-v3": {
    id: "recraft-v3",
    name: "🖌️ Recraft v3",
    description:
      "Быстро создаёт иллюстрации, иконки и графику в едином стиле. Отлично подходит для дизайна и презентаций.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "recraft-v4": {
    id: "recraft-v4",
    name: "🖌️ Recraft V4",
    description:
      "Recraft V4 создан специально для дизайна и маркетинга: чистая композиция, точный рендеринг текста и профессиональная полировка. Результат готов для кампании, презентации или страницы продукта без пост-обработки.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "recraft-v4-pro": {
    id: "recraft-v4-pro",
    name: "💠 Recraft V4 Pro",
    description:
      "Расширенная версия Recraft V4 с повышенным разрешением и детализацией. Идеальна для ответственных дизайн-проектов, где требуется максимальная визуальная точность — без правок, прямо в производство.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.25,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "recraft-v4-vector": {
    id: "recraft-v4-vector",
    name: "📐 Recraft V4 Vector (SVG)",
    description:
      "Генерирует масштабируемые SVG-векторы — идеально для логотипов, иллюстраций и иконок. Результат масштабируется без потери качества до любого размера и готов к прямому использованию в вёрстке и полиграфии.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.08,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "recraft-v4-pro-vector": {
    id: "recraft-v4-pro-vector",
    name: "📐 Recraft V4 Pro Vector (SVG)",
    description:
      "Профессиональная векторная генерация с максимальным качеством SVG. Подходит для сложных иллюстраций, брендинга и любого дизайна, требующего безупречной масштабируемости и детализации.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.3,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "seedream-5": {
    id: "seedream-5",
    name: "🛍️ Seedream 5.0 (ByteDance)",
    description:
      "Идеально для товарных фото, одежды и каталогов. Создаёт чистые, профессиональные изображения для продаж.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.035,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  "seedream-4.5": {
    id: "seedream-4.5",
    name: "🛍️ Seedream 4.5",
    description:
      "Предыдущая версия Seedream — чуть проще, но быстрее и дешевле. Подойдёт для массовой генерации товарных фото.",
    section: "design",
    provider: "fal",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },

  // ── Видео ─────────────────────────────────────────────────────────────────
  kling: {
    id: "kling",
    name: "Kling 2.0",
    description:
      "Передовая китайская видеомодель. Высокое качество движения, реалистичная физика и поддержка анимации по изображению.",
    section: "video",
    provider: "kling",
    costUsdPerRequest: 0.525, // 5s clip ~$0.35–$0.70
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: [5, 10],
  },
  sora: {
    id: "sora",
    name: "SORA",
    description:
      "Флагманская видеомодель OpenAI. Впечатляющее понимание физики мира, плавные движения и высокий уровень кинематографичности.",
    section: "video",
    provider: "openai",
    costUsdPerRequest: 0.5, // 5s @ $0.10/s
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: [4, 8, 12], // sora-2 discrete values
  },
  runway: {
    id: "runway",
    name: "RunWay",
    description:
      "Профессиональный инструмент для видеопроизводства. Гибкое управление длительностью, высокая стабильность и контроль над движением.",
    section: "video",
    provider: "runway",
    costUsdPerRequest: 0.75, // 5s clip ~$0.50–$1.00
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1280:768", "768:1280", "1104:832", "832:1104"],
    durationRange: { min: 2, max: 10 }, // Gen-4: any integer 2–10s
  },
  veo: {
    id: "veo",
    name: "Veo",
    description:
      "Видеомодель Google с высоким реализмом. Отлично справляется с природными сценами, динамикой воды и кинематографическими кадрами.",
    section: "video",
    provider: "google",
    costUsdPerRequest: 0.75, // 5s @ $0.15/s
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16"],
    durationRange: { min: 5, max: 8 }, // veo-2: any integer 5–8s
  },
  luma: {
    id: "luma",
    name: "Luma: DM",
    description:
      "Универсальная видеомодель с широким набором форматов кадра. Хороша для коротких динамичных клипов и анимации изображений.",
    section: "video",
    provider: "luma",
    costUsdPerRequest: 0.079, // ~$0.033–$0.125/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "4:3", "3:4", "1:1", "21:9"],
    supportedDurations: [5, 9], // "5s" / "9s"
  },
  minimax: {
    id: "minimax",
    name: "MiniMax",
    description:
      "Китайская видеомодель с отличным качеством движения персонажей. Генерирует 6-секундные клипы с высокой плавностью.",
    section: "video",
    provider: "minimax",
    costUsdPerRequest: 0.25, // ~$0.10–$0.40/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: null, // fixed 6s
  },
  pika: {
    id: "pika",
    name: "Pika",
    description:
      "Простой и доступный инструмент для создания коротких видеоклипов. Хорош для анимации изображений и быстрых творческих экспериментов.",
    section: "video",
    provider: "pika",
    costUsdPerRequest: 0.25, // ~$0.10–$0.40/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: [3, 5, 10],
  },
  hailuo: {
    id: "hailuo",
    name: "Hailuo",
    description:
      "Видеомодель с акцентом на плавность и кинематографичность. Поддерживает анимацию изображений и генерирует 6-секундные клипы.",
    section: "video",
    provider: "hailuo",
    costUsdPerRequest: 0.25, // ~$0.10–$0.40/gen
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: null, // fixed 6s
  },
  wan: {
    id: "wan",
    name: "Wan 2.1",
    description:
      "Открытая видеомодель от Alibaba. Доступная и качественная генерация коротких клипов с поддержкой анимации по изображению.",
    section: "video",
    provider: "fal",
    costUsdPerRequest: 0.06,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: [5],
  },
  heygen: {
    id: "heygen",
    name: "HeyGen",
    description:
      "Специализируется на создании видео с говорящими аватарами. Идеально для обучающего и маркетингового контента.",
    section: "video",
    provider: "heygen",
    costUsdPerRequest: 1.5, // ~$1–$2/min video
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: null, // avatar duration is script-driven
  },
  "d-id": {
    id: "d-id",
    name: "D-ID",
    description:
      "Оживляет фотографии и аватары. Синхронизирует речь с движением губ для создания реалистичных говорящих персонажей.",
    section: "video",
    provider: "d-id",
    costUsdPerRequest: 0.3, // ~$0.10–$0.50/clip
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["16:9", "9:16", "1:1"],
    supportedDurations: null, // script-driven
  },

  // ── Аудио ─────────────────────────────────────────────────────────────────
  "tts-openai": {
    id: "tts-openai",
    name: "Синтез речи (OpenAI)",
    description:
      "Синтез речи от OpenAI. Несколько голосов, естественная интонация и быстрая генерация для любого текста.",
    section: "audio",
    provider: "openai",
    costUsdPerRequest: 0.0045, // $0.015/1K chars, ~300 chars typical
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "voice-clone": {
    id: "voice-clone",
    name: "Клонирование голоса",
    description:
      "Клонирование голоса с высокой точностью. Воспроизводит тембр и интонации исходного голоса по короткому аудиообразцу.",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0.072, // ElevenLabs ~$0.054–$0.090 per ~300 chars
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  suno: {
    id: "suno",
    name: "Генерация музыки (Suno)",
    description:
      "Генерирует полноценные музыкальные треки с вокалом и аранжировкой по текстовому описанию стиля и настроения.",
    section: "audio",
    provider: "suno",
    costUsdPerRequest: 0.035, // ~$0.030–$0.040/track
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
  "sounds-el": {
    id: "sounds-el",
    name: "Звуковые эффекты (ElevenLabs)",
    description:
      "Генерирует оригинальные звуковые эффекты по описанию. Подходит для видеопроизводства, игр и подкастов.",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0.048, // ElevenLabs ~$0.036–$0.060 per ~200 chars
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
  },
};

// Модели по секции
export const MODELS_BY_SECTION = Object.values(AI_MODELS).reduce(
  (acc, model) => {
    if (!acc[model.section]) acc[model.section] = [];
    acc[model.section].push(model);
    return acc;
  },
  {} as Record<string, AIModel[]>,
);
